version: '3.8'
name: app-template_prod

services:
  app-template_web:
    build:
      context: .
      dockerfile: ./web/Dockerfile.prod
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production

  app-template_api:
    build:
      context: .
      dockerfile: ./api/Dockerfile.prod
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=${VIRTUAL_HOST:-trekie.dorkodu.com}
      - VIRTUAL_PORT=${API_PORT:-8001}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST:-trekie.dorkodu.com}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL:-hey@dorkodu.com}
      - VIRTUAL_PATH=/api
    expose:
      - ${API_PORT:-8001}
    restart: always
    networks:
      - app
      - nginx-proxy

  forum_postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-app}
      - PGPORT=${POSTGRES_PORT:-7000}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - app
      - nginx-proxy

volumes:
  pgdata:

networks:
  nginx-proxy:
    external: true
  app: