/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WwwRouteImport } from './routes/_www'
import { Route as WwwIndexRouteImport } from './routes/_www/index'
import { Route as Www404RouteImport } from './routes/_www/404'

const WwwRoute = WwwRouteImport.update({
  id: '/_www',
  getParentRoute: () => rootRouteImport,
} as any)
const WwwIndexRoute = WwwIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WwwRoute,
} as any)
const Www404Route = Www404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => WwwRoute,
} as any)

export interface FileRoutesByFullPath {
  '/404': typeof Www404Route
  '/': typeof WwwIndexRoute
}
export interface FileRoutesByTo {
  '/404': typeof Www404Route
  '/': typeof WwwIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_www': typeof WwwRouteWithChildren
  '/_www/404': typeof Www404Route
  '/_www/': typeof WwwIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/404' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/404' | '/'
  id: '__root__' | '/_www' | '/_www/404' | '/_www/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  WwwRoute: typeof WwwRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_www': {
      id: '/_www'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof WwwRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_www/': {
      id: '/_www/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof WwwIndexRouteImport
      parentRoute: typeof WwwRoute
    }
    '/_www/404': {
      id: '/_www/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof Www404RouteImport
      parentRoute: typeof WwwRoute
    }
  }
}

interface WwwRouteChildren {
  Www404Route: typeof Www404Route
  WwwIndexRoute: typeof WwwIndexRoute
}

const WwwRouteChildren: WwwRouteChildren = {
  Www404Route: Www404Route,
  WwwIndexRoute: WwwIndexRoute,
}

const WwwRouteWithChildren = WwwRoute._addFileChildren(WwwRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  WwwRoute: WwwRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
