/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WwwImport } from './routes/_www'
import { Route as AppImport } from './routes/_app'
import { Route as WwwIndexImport } from './routes/_www/index'
import { Route as WwwWelcomeImport } from './routes/_www/welcome'
import { Route as WwwLoginImport } from './routes/_www/login'
import { Route as WwwLegalImport } from './routes/_www/legal'
import { Route as WwwErrorImport } from './routes/_www/error'
import { Route as WwwCreateAccountImport } from './routes/_www/create-account'
import { Route as WwwAboutImport } from './routes/_www/about'
import { Route as Www404Import } from './routes/_www/404'
import { Route as AppPremiumImport } from './routes/_app/premium'
import { Route as AppMeImport } from './routes/_app/me'
import { Route as AppLifeImport } from './routes/_app/life'
import { Route as AppHomeImport } from './routes/_app/home'
import { Route as AppExploreImport } from './routes/_app/explore'
import { Route as AppArchiveImport } from './routes/_app/archive'
import { Route as AppSocialImport } from './routes/_app/Social'
import { Route as AppProfileImport } from './routes/_app/Profile'
import { Route as WwwHelpIndexImport } from './routes/_www/help/index'
import { Route as AppSettingsIndexImport } from './routes/_app/settings/index'
import { Route as AppMarketIndexImport } from './routes/_app/market/index'
import { Route as AppCommunityIndexImport } from './routes/_app/community/index'
import { Route as AppProfileEditImport } from './routes/_app/profile/edit'
import { Route as AppProfileUsernameImport } from './routes/_app/profile/$username'
import { Route as AppCommunityIdImport } from './routes/_app/community/$id'

// Create/Update Routes

const WwwRoute = WwwImport.update({
  id: '/_www',
  getParentRoute: () => rootRoute,
} as any)

const AppRoute = AppImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const WwwIndexRoute = WwwIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WwwRoute,
} as any)

const WwwWelcomeRoute = WwwWelcomeImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => WwwRoute,
} as any)

const WwwLoginRoute = WwwLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => WwwRoute,
} as any)

const WwwLegalRoute = WwwLegalImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => WwwRoute,
} as any)

const WwwErrorRoute = WwwErrorImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => WwwRoute,
} as any)

const WwwCreateAccountRoute = WwwCreateAccountImport.update({
  id: '/create-account',
  path: '/create-account',
  getParentRoute: () => WwwRoute,
} as any)

const WwwAboutRoute = WwwAboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => WwwRoute,
} as any)

const Www404Route = Www404Import.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => WwwRoute,
} as any)

const AppPremiumRoute = AppPremiumImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => AppRoute,
} as any)

const AppMeRoute = AppMeImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AppRoute,
} as any)

const AppLifeRoute = AppLifeImport.update({
  id: '/life',
  path: '/life',
  getParentRoute: () => AppRoute,
} as any)

const AppHomeRoute = AppHomeImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)

const AppExploreRoute = AppExploreImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AppRoute,
} as any)

const AppArchiveRoute = AppArchiveImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => AppRoute,
} as any)

const AppSocialRoute = AppSocialImport.update({
  id: '/Social',
  path: '/Social',
  getParentRoute: () => AppRoute,
} as any)

const AppProfileRoute = AppProfileImport.update({
  id: '/Profile',
  path: '/Profile',
  getParentRoute: () => AppRoute,
} as any)

const WwwHelpIndexRoute = WwwHelpIndexImport.update({
  id: '/help/',
  path: '/help/',
  getParentRoute: () => WwwRoute,
} as any)

const AppSettingsIndexRoute = AppSettingsIndexImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)

const AppMarketIndexRoute = AppMarketIndexImport.update({
  id: '/market/',
  path: '/market/',
  getParentRoute: () => AppRoute,
} as any)

const AppCommunityIndexRoute = AppCommunityIndexImport.update({
  id: '/community/',
  path: '/community/',
  getParentRoute: () => AppRoute,
} as any)

const AppProfileEditRoute = AppProfileEditImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => AppRoute,
} as any)

const AppProfileUsernameRoute = AppProfileUsernameImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => AppRoute,
} as any)

const AppCommunityIdRoute = AppCommunityIdImport.update({
  id: '/community/$id',
  path: '/community/$id',
  getParentRoute: () => AppRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/_www': {
      id: '/_www'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof WwwImport
      parentRoute: typeof rootRoute
    }
    '/_app/Profile': {
      id: '/_app/Profile'
      path: '/Profile'
      fullPath: '/Profile'
      preLoaderRoute: typeof AppProfileImport
      parentRoute: typeof AppImport
    }
    '/_app/Social': {
      id: '/_app/Social'
      path: '/Social'
      fullPath: '/Social'
      preLoaderRoute: typeof AppSocialImport
      parentRoute: typeof AppImport
    }
    '/_app/archive': {
      id: '/_app/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof AppArchiveImport
      parentRoute: typeof AppImport
    }
    '/_app/explore': {
      id: '/_app/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AppExploreImport
      parentRoute: typeof AppImport
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeImport
      parentRoute: typeof AppImport
    }
    '/_app/life': {
      id: '/_app/life'
      path: '/life'
      fullPath: '/life'
      preLoaderRoute: typeof AppLifeImport
      parentRoute: typeof AppImport
    }
    '/_app/me': {
      id: '/_app/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AppMeImport
      parentRoute: typeof AppImport
    }
    '/_app/premium': {
      id: '/_app/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof AppPremiumImport
      parentRoute: typeof AppImport
    }
    '/_www/404': {
      id: '/_www/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof Www404Import
      parentRoute: typeof WwwImport
    }
    '/_www/about': {
      id: '/_www/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof WwwAboutImport
      parentRoute: typeof WwwImport
    }
    '/_www/create-account': {
      id: '/_www/create-account'
      path: '/create-account'
      fullPath: '/create-account'
      preLoaderRoute: typeof WwwCreateAccountImport
      parentRoute: typeof WwwImport
    }
    '/_www/error': {
      id: '/_www/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof WwwErrorImport
      parentRoute: typeof WwwImport
    }
    '/_www/legal': {
      id: '/_www/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof WwwLegalImport
      parentRoute: typeof WwwImport
    }
    '/_www/login': {
      id: '/_www/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof WwwLoginImport
      parentRoute: typeof WwwImport
    }
    '/_www/welcome': {
      id: '/_www/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WwwWelcomeImport
      parentRoute: typeof WwwImport
    }
    '/_www/': {
      id: '/_www/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof WwwIndexImport
      parentRoute: typeof WwwImport
    }
    '/_app/community/$id': {
      id: '/_app/community/$id'
      path: '/community/$id'
      fullPath: '/community/$id'
      preLoaderRoute: typeof AppCommunityIdImport
      parentRoute: typeof AppImport
    }
    '/_app/profile/$username': {
      id: '/_app/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof AppProfileUsernameImport
      parentRoute: typeof AppImport
    }
    '/_app/profile/edit': {
      id: '/_app/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof AppProfileEditImport
      parentRoute: typeof AppImport
    }
    '/_app/community/': {
      id: '/_app/community/'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof AppCommunityIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/market/': {
      id: '/_app/market/'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof AppMarketIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsIndexImport
      parentRoute: typeof AppImport
    }
    '/_www/help/': {
      id: '/_www/help/'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof WwwHelpIndexImport
      parentRoute: typeof WwwImport
    }
  }
}

// Create and export the route tree

interface AppRouteChildren {
  AppProfileRoute: typeof AppProfileRoute
  AppSocialRoute: typeof AppSocialRoute
  AppArchiveRoute: typeof AppArchiveRoute
  AppExploreRoute: typeof AppExploreRoute
  AppHomeRoute: typeof AppHomeRoute
  AppLifeRoute: typeof AppLifeRoute
  AppMeRoute: typeof AppMeRoute
  AppPremiumRoute: typeof AppPremiumRoute
  AppCommunityIdRoute: typeof AppCommunityIdRoute
  AppProfileUsernameRoute: typeof AppProfileUsernameRoute
  AppProfileEditRoute: typeof AppProfileEditRoute
  AppCommunityIndexRoute: typeof AppCommunityIndexRoute
  AppMarketIndexRoute: typeof AppMarketIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppProfileRoute: AppProfileRoute,
  AppSocialRoute: AppSocialRoute,
  AppArchiveRoute: AppArchiveRoute,
  AppExploreRoute: AppExploreRoute,
  AppHomeRoute: AppHomeRoute,
  AppLifeRoute: AppLifeRoute,
  AppMeRoute: AppMeRoute,
  AppPremiumRoute: AppPremiumRoute,
  AppCommunityIdRoute: AppCommunityIdRoute,
  AppProfileUsernameRoute: AppProfileUsernameRoute,
  AppProfileEditRoute: AppProfileEditRoute,
  AppCommunityIndexRoute: AppCommunityIndexRoute,
  AppMarketIndexRoute: AppMarketIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface WwwRouteChildren {
  Www404Route: typeof Www404Route
  WwwAboutRoute: typeof WwwAboutRoute
  WwwCreateAccountRoute: typeof WwwCreateAccountRoute
  WwwErrorRoute: typeof WwwErrorRoute
  WwwLegalRoute: typeof WwwLegalRoute
  WwwLoginRoute: typeof WwwLoginRoute
  WwwWelcomeRoute: typeof WwwWelcomeRoute
  WwwIndexRoute: typeof WwwIndexRoute
  WwwHelpIndexRoute: typeof WwwHelpIndexRoute
}

const WwwRouteChildren: WwwRouteChildren = {
  Www404Route: Www404Route,
  WwwAboutRoute: WwwAboutRoute,
  WwwCreateAccountRoute: WwwCreateAccountRoute,
  WwwErrorRoute: WwwErrorRoute,
  WwwLegalRoute: WwwLegalRoute,
  WwwLoginRoute: WwwLoginRoute,
  WwwWelcomeRoute: WwwWelcomeRoute,
  WwwIndexRoute: WwwIndexRoute,
  WwwHelpIndexRoute: WwwHelpIndexRoute,
}

const WwwRouteWithChildren = WwwRoute._addFileChildren(WwwRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof WwwRouteWithChildren
  '/Profile': typeof AppProfileRoute
  '/Social': typeof AppSocialRoute
  '/archive': typeof AppArchiveRoute
  '/explore': typeof AppExploreRoute
  '/home': typeof AppHomeRoute
  '/life': typeof AppLifeRoute
  '/me': typeof AppMeRoute
  '/premium': typeof AppPremiumRoute
  '/404': typeof Www404Route
  '/about': typeof WwwAboutRoute
  '/create-account': typeof WwwCreateAccountRoute
  '/error': typeof WwwErrorRoute
  '/legal': typeof WwwLegalRoute
  '/login': typeof WwwLoginRoute
  '/welcome': typeof WwwWelcomeRoute
  '/': typeof WwwIndexRoute
  '/community/$id': typeof AppCommunityIdRoute
  '/profile/$username': typeof AppProfileUsernameRoute
  '/profile/edit': typeof AppProfileEditRoute
  '/community': typeof AppCommunityIndexRoute
  '/market': typeof AppMarketIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/help': typeof WwwHelpIndexRoute
}

export interface FileRoutesByTo {
  '': typeof AppRouteWithChildren
  '/Profile': typeof AppProfileRoute
  '/Social': typeof AppSocialRoute
  '/archive': typeof AppArchiveRoute
  '/explore': typeof AppExploreRoute
  '/home': typeof AppHomeRoute
  '/life': typeof AppLifeRoute
  '/me': typeof AppMeRoute
  '/premium': typeof AppPremiumRoute
  '/404': typeof Www404Route
  '/about': typeof WwwAboutRoute
  '/create-account': typeof WwwCreateAccountRoute
  '/error': typeof WwwErrorRoute
  '/legal': typeof WwwLegalRoute
  '/login': typeof WwwLoginRoute
  '/welcome': typeof WwwWelcomeRoute
  '/': typeof WwwIndexRoute
  '/community/$id': typeof AppCommunityIdRoute
  '/profile/$username': typeof AppProfileUsernameRoute
  '/profile/edit': typeof AppProfileEditRoute
  '/community': typeof AppCommunityIndexRoute
  '/market': typeof AppMarketIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/help': typeof WwwHelpIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_app': typeof AppRouteWithChildren
  '/_www': typeof WwwRouteWithChildren
  '/_app/Profile': typeof AppProfileRoute
  '/_app/Social': typeof AppSocialRoute
  '/_app/archive': typeof AppArchiveRoute
  '/_app/explore': typeof AppExploreRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/life': typeof AppLifeRoute
  '/_app/me': typeof AppMeRoute
  '/_app/premium': typeof AppPremiumRoute
  '/_www/404': typeof Www404Route
  '/_www/about': typeof WwwAboutRoute
  '/_www/create-account': typeof WwwCreateAccountRoute
  '/_www/error': typeof WwwErrorRoute
  '/_www/legal': typeof WwwLegalRoute
  '/_www/login': typeof WwwLoginRoute
  '/_www/welcome': typeof WwwWelcomeRoute
  '/_www/': typeof WwwIndexRoute
  '/_app/community/$id': typeof AppCommunityIdRoute
  '/_app/profile/$username': typeof AppProfileUsernameRoute
  '/_app/profile/edit': typeof AppProfileEditRoute
  '/_app/community/': typeof AppCommunityIndexRoute
  '/_app/market/': typeof AppMarketIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_www/help/': typeof WwwHelpIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/Profile'
    | '/Social'
    | '/archive'
    | '/explore'
    | '/home'
    | '/life'
    | '/me'
    | '/premium'
    | '/404'
    | '/about'
    | '/create-account'
    | '/error'
    | '/legal'
    | '/login'
    | '/welcome'
    | '/'
    | '/community/$id'
    | '/profile/$username'
    | '/profile/edit'
    | '/community'
    | '/market'
    | '/settings'
    | '/help'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/Profile'
    | '/Social'
    | '/archive'
    | '/explore'
    | '/home'
    | '/life'
    | '/me'
    | '/premium'
    | '/404'
    | '/about'
    | '/create-account'
    | '/error'
    | '/legal'
    | '/login'
    | '/welcome'
    | '/'
    | '/community/$id'
    | '/profile/$username'
    | '/profile/edit'
    | '/community'
    | '/market'
    | '/settings'
    | '/help'
  id:
    | '__root__'
    | '/_app'
    | '/_www'
    | '/_app/Profile'
    | '/_app/Social'
    | '/_app/archive'
    | '/_app/explore'
    | '/_app/home'
    | '/_app/life'
    | '/_app/me'
    | '/_app/premium'
    | '/_www/404'
    | '/_www/about'
    | '/_www/create-account'
    | '/_www/error'
    | '/_www/legal'
    | '/_www/login'
    | '/_www/welcome'
    | '/_www/'
    | '/_app/community/$id'
    | '/_app/profile/$username'
    | '/_app/profile/edit'
    | '/_app/community/'
    | '/_app/market/'
    | '/_app/settings/'
    | '/_www/help/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  WwwRoute: typeof WwwRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  WwwRoute: WwwRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_app",
        "/_www"
      ]
    },
    "/_app": {
      "filePath": "_app.tsx",
      "children": [
        "/_app/Profile",
        "/_app/Social",
        "/_app/archive",
        "/_app/explore",
        "/_app/home",
        "/_app/life",
        "/_app/me",
        "/_app/premium",
        "/_app/community/$id",
        "/_app/profile/$username",
        "/_app/profile/edit",
        "/_app/community/",
        "/_app/market/",
        "/_app/settings/"
      ]
    },
    "/_www": {
      "filePath": "_www.tsx",
      "children": [
        "/_www/404",
        "/_www/about",
        "/_www/create-account",
        "/_www/error",
        "/_www/legal",
        "/_www/login",
        "/_www/welcome",
        "/_www/",
        "/_www/help/"
      ]
    },
    "/_app/Profile": {
      "filePath": "_app/Profile.tsx",
      "parent": "/_app"
    },
    "/_app/Social": {
      "filePath": "_app/Social.tsx",
      "parent": "/_app"
    },
    "/_app/archive": {
      "filePath": "_app/archive.tsx",
      "parent": "/_app"
    },
    "/_app/explore": {
      "filePath": "_app/explore.tsx",
      "parent": "/_app"
    },
    "/_app/home": {
      "filePath": "_app/home.tsx",
      "parent": "/_app"
    },
    "/_app/life": {
      "filePath": "_app/life.tsx",
      "parent": "/_app"
    },
    "/_app/me": {
      "filePath": "_app/me.tsx",
      "parent": "/_app"
    },
    "/_app/premium": {
      "filePath": "_app/premium.tsx",
      "parent": "/_app"
    },
    "/_www/404": {
      "filePath": "_www/404.tsx",
      "parent": "/_www"
    },
    "/_www/about": {
      "filePath": "_www/about.tsx",
      "parent": "/_www"
    },
    "/_www/create-account": {
      "filePath": "_www/create-account.tsx",
      "parent": "/_www"
    },
    "/_www/error": {
      "filePath": "_www/error.tsx",
      "parent": "/_www"
    },
    "/_www/legal": {
      "filePath": "_www/legal.tsx",
      "parent": "/_www"
    },
    "/_www/login": {
      "filePath": "_www/login.tsx",
      "parent": "/_www"
    },
    "/_www/welcome": {
      "filePath": "_www/welcome.tsx",
      "parent": "/_www"
    },
    "/_www/": {
      "filePath": "_www/index.tsx",
      "parent": "/_www"
    },
    "/_app/community/$id": {
      "filePath": "_app/community/$id.tsx",
      "parent": "/_app"
    },
    "/_app/profile/$username": {
      "filePath": "_app/profile/$username.tsx",
      "parent": "/_app"
    },
    "/_app/profile/edit": {
      "filePath": "_app/profile/edit.tsx",
      "parent": "/_app"
    },
    "/_app/community/": {
      "filePath": "_app/community/index.tsx",
      "parent": "/_app"
    },
    "/_app/market/": {
      "filePath": "_app/market/index.tsx",
      "parent": "/_app"
    },
    "/_app/settings/": {
      "filePath": "_app/settings/index.tsx",
      "parent": "/_app"
    },
    "/_www/help/": {
      "filePath": "_www/help/index.tsx",
      "parent": "/_www"
    }
  }
}
ROUTE_MANIFEST_END */
