/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AppImport } from './routes/_app'
import { Route as WwwIndexImport } from './www/index'
import { Route as WwwWelcomeImport } from './www/welcome'
import { Route as WwwLoginImport } from './www/login'
import { Route as WwwLegalImport } from './www/legal'
import { Route as WwwErrorImport } from './www/error'
import { Route as WwwCreateAccountImport } from './www/create-account'
import { Route as WwwAboutImport } from './www/about'
import { Route as WwwLayoutImport } from './www/_layout'
import { Route as Www404Import } from './www/404'
import { Route as AppCommunityImport } from './routes/app/community'
import { Route as AppArchiveImport } from './routes/app/archive'
import { Route as AppSocialImport } from './routes/app/Social'
import { Route as AppSettingsImport } from './routes/app/Settings'
import { Route as AppProfileImport } from './routes/app/Profile'
import { Route as AppPremiumImport } from './routes/app/premium'
import { Route as AppMeImport } from './routes/app/Me'
import { Route as AppMarketImport } from './routes/app/market'
import { Route as AppLifeImport } from './routes/app/life'
import { Route as AppHomeImport } from './routes/app/home'
import { Route as AppHelpImport } from './routes/app/help'
import { Route as AppExploreImport } from './routes/app/explore'
import { Route as AppDataImport } from './routes/app/my-data'
import { Route as AppCommunityPageImport } from './routes/app/community/$page'

// Create Virtual Routes

const WwwImport = createFileRoute('/www')()

// Create/Update Routes

const WwwRoute = WwwImport.update({
  id: '/www',
  path: '/www',
  getParentRoute: () => rootRoute,
} as any)

const AppRoute = AppImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const WwwIndexRoute = WwwIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WwwRoute,
} as any)

const WwwWelcomeRoute = WwwWelcomeImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => WwwRoute,
} as any)

const WwwLoginRoute = WwwLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => WwwRoute,
} as any)

const WwwLegalRoute = WwwLegalImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => WwwRoute,
} as any)

const WwwErrorRoute = WwwErrorImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => WwwRoute,
} as any)

const WwwCreateAccountRoute = WwwCreateAccountImport.update({
  id: '/create-account',
  path: '/create-account',
  getParentRoute: () => WwwRoute,
} as any)

const WwwAboutRoute = WwwAboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => WwwRoute,
} as any)

const WwwLayoutRoute = WwwLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => WwwRoute,
} as any)

const Www404Route = Www404Import.update({
  id: '/www/404',
  path: '/www/404',
  getParentRoute: () => rootRoute,
} as any)

const AppCommunityRoute = AppCommunityImport.update({
  id: '/app/community',
  path: '/app/community',
  getParentRoute: () => rootRoute,
} as any)

const AppArchiveRoute = AppArchiveImport.update({
  id: '/app/archive',
  path: '/app/archive',
  getParentRoute: () => rootRoute,
} as any)

const AppSocialRoute = AppSocialImport.update({
  id: '/app/Social',
  path: '/app/Social',
  getParentRoute: () => rootRoute,
} as any)

const AppSettingsRoute = AppSettingsImport.update({
  id: '/app/Settings',
  path: '/app/Settings',
  getParentRoute: () => rootRoute,
} as any)

const AppProfileRoute = AppProfileImport.update({
  id: '/app/Profile',
  path: '/app/Profile',
  getParentRoute: () => rootRoute,
} as any)

const AppPremiumRoute = AppPremiumImport.update({
  id: '/app/Premium',
  path: '/app/Premium',
  getParentRoute: () => rootRoute,
} as any)

const AppMeRoute = AppMeImport.update({
  id: '/app/Me',
  path: '/app/Me',
  getParentRoute: () => rootRoute,
} as any)

const AppMarketRoute = AppMarketImport.update({
  id: '/app/Market',
  path: '/app/Market',
  getParentRoute: () => rootRoute,
} as any)

const AppLifeRoute = AppLifeImport.update({
  id: '/app/Life',
  path: '/app/Life',
  getParentRoute: () => rootRoute,
} as any)

const AppHomeRoute = AppHomeImport.update({
  id: '/app/Home',
  path: '/app/Home',
  getParentRoute: () => rootRoute,
} as any)

const AppHelpRoute = AppHelpImport.update({
  id: '/app/Help',
  path: '/app/Help',
  getParentRoute: () => rootRoute,
} as any)

const AppExploreRoute = AppExploreImport.update({
  id: '/app/Explore',
  path: '/app/Explore',
  getParentRoute: () => rootRoute,
} as any)

const AppDataRoute = AppDataImport.update({
  id: '/app/Data',
  path: '/app/Data',
  getParentRoute: () => rootRoute,
} as any)

const AppCommunityPageRoute = AppCommunityPageImport.update({
  id: '/app/CommunityPage',
  path: '/app/CommunityPage',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/app/CommunityPage': {
      id: '/app/CommunityPage'
      path: '/app/CommunityPage'
      fullPath: '/app/CommunityPage'
      preLoaderRoute: typeof AppCommunityPageImport
      parentRoute: typeof rootRoute
    }
    '/app/Data': {
      id: '/app/Data'
      path: '/app/Data'
      fullPath: '/app/Data'
      preLoaderRoute: typeof AppDataImport
      parentRoute: typeof rootRoute
    }
    '/app/Explore': {
      id: '/app/Explore'
      path: '/app/Explore'
      fullPath: '/app/Explore'
      preLoaderRoute: typeof AppExploreImport
      parentRoute: typeof rootRoute
    }
    '/app/Help': {
      id: '/app/Help'
      path: '/app/Help'
      fullPath: '/app/Help'
      preLoaderRoute: typeof AppHelpImport
      parentRoute: typeof rootRoute
    }
    '/app/Home': {
      id: '/app/Home'
      path: '/app/Home'
      fullPath: '/app/Home'
      preLoaderRoute: typeof AppHomeImport
      parentRoute: typeof rootRoute
    }
    '/app/Life': {
      id: '/app/Life'
      path: '/app/Life'
      fullPath: '/app/Life'
      preLoaderRoute: typeof AppLifeImport
      parentRoute: typeof rootRoute
    }
    '/app/Market': {
      id: '/app/Market'
      path: '/app/Market'
      fullPath: '/app/Market'
      preLoaderRoute: typeof AppMarketImport
      parentRoute: typeof rootRoute
    }
    '/app/Me': {
      id: '/app/Me'
      path: '/app/Me'
      fullPath: '/app/Me'
      preLoaderRoute: typeof AppMeImport
      parentRoute: typeof rootRoute
    }
    '/app/Premium': {
      id: '/app/Premium'
      path: '/app/Premium'
      fullPath: '/app/Premium'
      preLoaderRoute: typeof AppPremiumImport
      parentRoute: typeof rootRoute
    }
    '/app/Profile': {
      id: '/app/Profile'
      path: '/app/Profile'
      fullPath: '/app/Profile'
      preLoaderRoute: typeof AppProfileImport
      parentRoute: typeof rootRoute
    }
    '/app/Settings': {
      id: '/app/Settings'
      path: '/app/Settings'
      fullPath: '/app/Settings'
      preLoaderRoute: typeof AppSettingsImport
      parentRoute: typeof rootRoute
    }
    '/app/Social': {
      id: '/app/Social'
      path: '/app/Social'
      fullPath: '/app/Social'
      preLoaderRoute: typeof AppSocialImport
      parentRoute: typeof rootRoute
    }
    '/app/archive': {
      id: '/app/archive'
      path: '/app/archive'
      fullPath: '/app/archive'
      preLoaderRoute: typeof AppArchiveImport
      parentRoute: typeof rootRoute
    }
    '/app/community': {
      id: '/app/community'
      path: '/app/community'
      fullPath: '/app/community'
      preLoaderRoute: typeof AppCommunityImport
      parentRoute: typeof rootRoute
    }
    '/www/404': {
      id: '/www/404'
      path: '/www/404'
      fullPath: '/www/404'
      preLoaderRoute: typeof Www404Import
      parentRoute: typeof rootRoute
    }
    '/www': {
      id: '/www'
      path: '/www'
      fullPath: '/www'
      preLoaderRoute: typeof WwwImport
      parentRoute: typeof rootRoute
    }
    '/www/_layout': {
      id: '/www/_layout'
      path: '/www'
      fullPath: '/www'
      preLoaderRoute: typeof WwwLayoutImport
      parentRoute: typeof WwwRoute
    }
    '/www/about': {
      id: '/www/about'
      path: '/about'
      fullPath: '/www/about'
      preLoaderRoute: typeof WwwAboutImport
      parentRoute: typeof WwwImport
    }
    '/www/create-account': {
      id: '/www/create-account'
      path: '/create-account'
      fullPath: '/www/create-account'
      preLoaderRoute: typeof WwwCreateAccountImport
      parentRoute: typeof WwwImport
    }
    '/www/error': {
      id: '/www/error'
      path: '/error'
      fullPath: '/www/error'
      preLoaderRoute: typeof WwwErrorImport
      parentRoute: typeof WwwImport
    }
    '/www/legal': {
      id: '/www/legal'
      path: '/legal'
      fullPath: '/www/legal'
      preLoaderRoute: typeof WwwLegalImport
      parentRoute: typeof WwwImport
    }
    '/www/login': {
      id: '/www/login'
      path: '/login'
      fullPath: '/www/login'
      preLoaderRoute: typeof WwwLoginImport
      parentRoute: typeof WwwImport
    }
    '/www/welcome': {
      id: '/www/welcome'
      path: '/welcome'
      fullPath: '/www/welcome'
      preLoaderRoute: typeof WwwWelcomeImport
      parentRoute: typeof WwwImport
    }
    '/www/': {
      id: '/www/'
      path: '/'
      fullPath: '/www/'
      preLoaderRoute: typeof WwwIndexImport
      parentRoute: typeof WwwImport
    }
  }
}

// Create and export the route tree

interface WwwRouteChildren {
  WwwLayoutRoute: typeof WwwLayoutRoute
  WwwAboutRoute: typeof WwwAboutRoute
  WwwCreateAccountRoute: typeof WwwCreateAccountRoute
  WwwErrorRoute: typeof WwwErrorRoute
  WwwLegalRoute: typeof WwwLegalRoute
  WwwLoginRoute: typeof WwwLoginRoute
  WwwWelcomeRoute: typeof WwwWelcomeRoute
  WwwIndexRoute: typeof WwwIndexRoute
}

const WwwRouteChildren: WwwRouteChildren = {
  WwwLayoutRoute: WwwLayoutRoute,
  WwwAboutRoute: WwwAboutRoute,
  WwwCreateAccountRoute: WwwCreateAccountRoute,
  WwwErrorRoute: WwwErrorRoute,
  WwwLegalRoute: WwwLegalRoute,
  WwwLoginRoute: WwwLoginRoute,
  WwwWelcomeRoute: WwwWelcomeRoute,
  WwwIndexRoute: WwwIndexRoute,
}

const WwwRouteWithChildren = WwwRoute._addFileChildren(WwwRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AppRoute
  '/app/CommunityPage': typeof AppCommunityPageRoute
  '/app/Data': typeof AppDataRoute
  '/app/Explore': typeof AppExploreRoute
  '/app/Help': typeof AppHelpRoute
  '/app/Home': typeof AppHomeRoute
  '/app/Life': typeof AppLifeRoute
  '/app/Market': typeof AppMarketRoute
  '/app/Me': typeof AppMeRoute
  '/app/Premium': typeof AppPremiumRoute
  '/app/Profile': typeof AppProfileRoute
  '/app/Settings': typeof AppSettingsRoute
  '/app/Social': typeof AppSocialRoute
  '/app/archive': typeof AppArchiveRoute
  '/app/community': typeof AppCommunityRoute
  '/www/404': typeof Www404Route
  '/www': typeof WwwLayoutRoute
  '/www/about': typeof WwwAboutRoute
  '/www/create-account': typeof WwwCreateAccountRoute
  '/www/error': typeof WwwErrorRoute
  '/www/legal': typeof WwwLegalRoute
  '/www/login': typeof WwwLoginRoute
  '/www/welcome': typeof WwwWelcomeRoute
  '/www/': typeof WwwIndexRoute
}

export interface FileRoutesByTo {
  '': typeof AppRoute
  '/app/CommunityPage': typeof AppCommunityPageRoute
  '/app/Data': typeof AppDataRoute
  '/app/Explore': typeof AppExploreRoute
  '/app/Help': typeof AppHelpRoute
  '/app/Home': typeof AppHomeRoute
  '/app/Life': typeof AppLifeRoute
  '/app/Market': typeof AppMarketRoute
  '/app/Me': typeof AppMeRoute
  '/app/Premium': typeof AppPremiumRoute
  '/app/Profile': typeof AppProfileRoute
  '/app/Settings': typeof AppSettingsRoute
  '/app/Social': typeof AppSocialRoute
  '/app/archive': typeof AppArchiveRoute
  '/app/community': typeof AppCommunityRoute
  '/www/404': typeof Www404Route
  '/www': typeof WwwIndexRoute
  '/www/about': typeof WwwAboutRoute
  '/www/create-account': typeof WwwCreateAccountRoute
  '/www/error': typeof WwwErrorRoute
  '/www/legal': typeof WwwLegalRoute
  '/www/login': typeof WwwLoginRoute
  '/www/welcome': typeof WwwWelcomeRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_app': typeof AppRoute
  '/app/CommunityPage': typeof AppCommunityPageRoute
  '/app/Data': typeof AppDataRoute
  '/app/Explore': typeof AppExploreRoute
  '/app/Help': typeof AppHelpRoute
  '/app/Home': typeof AppHomeRoute
  '/app/Life': typeof AppLifeRoute
  '/app/Market': typeof AppMarketRoute
  '/app/Me': typeof AppMeRoute
  '/app/Premium': typeof AppPremiumRoute
  '/app/Profile': typeof AppProfileRoute
  '/app/Settings': typeof AppSettingsRoute
  '/app/Social': typeof AppSocialRoute
  '/app/archive': typeof AppArchiveRoute
  '/app/community': typeof AppCommunityRoute
  '/www/404': typeof Www404Route
  '/www': typeof WwwRouteWithChildren
  '/www/_layout': typeof WwwLayoutRoute
  '/www/about': typeof WwwAboutRoute
  '/www/create-account': typeof WwwCreateAccountRoute
  '/www/error': typeof WwwErrorRoute
  '/www/legal': typeof WwwLegalRoute
  '/www/login': typeof WwwLoginRoute
  '/www/welcome': typeof WwwWelcomeRoute
  '/www/': typeof WwwIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
  | ''
  | '/app/CommunityPage'
  | '/app/Data'
  | '/app/Explore'
  | '/app/Help'
  | '/app/Home'
  | '/app/Life'
  | '/app/Market'
  | '/app/Me'
  | '/app/Premium'
  | '/app/Profile'
  | '/app/Settings'
  | '/app/Social'
  | '/app/archive'
  | '/app/community'
  | '/www/404'
  | '/www'
  | '/www/about'
  | '/www/create-account'
  | '/www/error'
  | '/www/legal'
  | '/www/login'
  | '/www/welcome'
  | '/www/'
  fileRoutesByTo: FileRoutesByTo
  to:
  | ''
  | '/app/CommunityPage'
  | '/app/Data'
  | '/app/Explore'
  | '/app/Help'
  | '/app/Home'
  | '/app/Life'
  | '/app/Market'
  | '/app/Me'
  | '/app/Premium'
  | '/app/Profile'
  | '/app/Settings'
  | '/app/Social'
  | '/app/archive'
  | '/app/community'
  | '/www/404'
  | '/www'
  | '/www/about'
  | '/www/create-account'
  | '/www/error'
  | '/www/legal'
  | '/www/login'
  | '/www/welcome'
  id:
  | '__root__'
  | '/_app'
  | '/app/CommunityPage'
  | '/app/Data'
  | '/app/Explore'
  | '/app/Help'
  | '/app/Home'
  | '/app/Life'
  | '/app/Market'
  | '/app/Me'
  | '/app/Premium'
  | '/app/Profile'
  | '/app/Settings'
  | '/app/Social'
  | '/app/archive'
  | '/app/community'
  | '/www/404'
  | '/www'
  | '/www/_layout'
  | '/www/about'
  | '/www/create-account'
  | '/www/error'
  | '/www/legal'
  | '/www/login'
  | '/www/welcome'
  | '/www/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AppRoute: typeof AppRoute
  AppCommunityPageRoute: typeof AppCommunityPageRoute
  AppDataRoute: typeof AppDataRoute
  AppExploreRoute: typeof AppExploreRoute
  AppHelpRoute: typeof AppHelpRoute
  AppHomeRoute: typeof AppHomeRoute
  AppLifeRoute: typeof AppLifeRoute
  AppMarketRoute: typeof AppMarketRoute
  AppMeRoute: typeof AppMeRoute
  AppPremiumRoute: typeof AppPremiumRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSocialRoute: typeof AppSocialRoute
  AppArchiveRoute: typeof AppArchiveRoute
  AppCommunityRoute: typeof AppCommunityRoute
  Www404Route: typeof Www404Route
  WwwRoute: typeof WwwRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRoute,
  AppCommunityPageRoute: AppCommunityPageRoute,
  AppDataRoute: AppDataRoute,
  AppExploreRoute: AppExploreRoute,
  AppHelpRoute: AppHelpRoute,
  AppHomeRoute: AppHomeRoute,
  AppLifeRoute: AppLifeRoute,
  AppMarketRoute: AppMarketRoute,
  AppMeRoute: AppMeRoute,
  AppPremiumRoute: AppPremiumRoute,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSocialRoute: AppSocialRoute,
  AppArchiveRoute: AppArchiveRoute,
  AppCommunityRoute: AppCommunityRoute,
  Www404Route: Www404Route,
  WwwRoute: WwwRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_app",
        "/app/CommunityPage",
        "/app/Data",
        "/app/Explore",
        "/app/Help",
        "/app/Home",
        "/app/Life",
        "/app/Market",
        "/app/Me",
        "/app/Premium",
        "/app/Profile",
        "/app/Settings",
        "/app/Social",
        "/app/archive",
        "/app/community",
        "/www/404",
        "/www"
      ]
    },
    "/_app": {
      "filePath": "_app.tsx"
    },
    "/app/CommunityPage": {
      "filePath": "app/CommunityPage.tsx"
    },
    "/app/Data": {
      "filePath": "app/Data.tsx"
    },
    "/app/Explore": {
      "filePath": "app/Explore.tsx"
    },
    "/app/Help": {
      "filePath": "app/Help.tsx"
    },
    "/app/Home": {
      "filePath": "app/Home.tsx"
    },
    "/app/Life": {
      "filePath": "app/Life.tsx"
    },
    "/app/Market": {
      "filePath": "app/Market.tsx"
    },
    "/app/Me": {
      "filePath": "app/Me.tsx"
    },
    "/app/Premium": {
      "filePath": "app/Premium.tsx"
    },
    "/app/Profile": {
      "filePath": "app/Profile.tsx"
    },
    "/app/Settings": {
      "filePath": "app/Settings.tsx"
    },
    "/app/Social": {
      "filePath": "app/Social.tsx"
    },
    "/app/archive": {
      "filePath": "app/archive.tsx"
    },
    "/app/community": {
      "filePath": "app/community.tsx"
    },
    "/www/404": {
      "filePath": "www/404.tsx"
    },
    "/www": {
      "filePath": "www",
      "children": [
        "/www/_layout",
        "/www/about",
        "/www/create-account",
        "/www/error",
        "/www/legal",
        "/www/login",
        "/www/welcome",
        "/www/"
      ]
    },
    "/www/_layout": {
      "filePath": "www/_layout.tsx",
      "parent": "/www"
    },
    "/www/about": {
      "filePath": "www/about.tsx",
      "parent": "/www"
    },
    "/www/create-account": {
      "filePath": "www/create-account.tsx",
      "parent": "/www"
    },
    "/www/error": {
      "filePath": "www/error.tsx",
      "parent": "/www"
    },
    "/www/legal": {
      "filePath": "www/legal.tsx",
      "parent": "/www"
    },
    "/www/login": {
      "filePath": "www/login.tsx",
      "parent": "/www"
    },
    "/www/welcome": {
      "filePath": "www/welcome.tsx",
      "parent": "/www"
    },
    "/www/": {
      "filePath": "www/index.tsx",
      "parent": "/www"
    }
  }
}
ROUTE_MANIFEST_END */
