FROM node:20-alpine AS base
RUN corepack enable && pnpm config set --global store-dir /root/.local/share/pnpm/store/v3

WORKDIR /api
COPY ./api/pnpm-lock.yaml /api

FROM base AS build
RUN pnpm fetch
COPY ./api /api
RUN pnpm install --offline && pnpm run build

FROM base
COPY --from=build /api/dist /api/package.json /api
RUN pnpm install --prod
CMD [ "node", "/api/dist/index.js" ]