FROM node:16-alpine
WORKDIR /trekie

RUN mkdir -p /trekie/api
RUN mkdir -p /trekie/shared

RUN npm install -g pnpm

COPY ./api/pnpm-lock.yaml /trekie/api
RUN cd api && pnpm fetch
COPY ./api /trekie/api
COPY ./shared /trekie/shared
RUN cd api && pnpm install --offline

WORKDIR /trekie/api
CMD [ "pnpm", "run", "dev" ]