FROM node:20-alpine AS base
RUN corepack enable && pnpm config set --global store-dir /root/.local/share/pnpm/store/v3
WORKDIR /api

COPY ./api/pnpm-lock.yaml /api
RUN pnpm fetch

COPY ./api /api
RUN pnpm install --offline

CMD [ "pnpm", "run", "dev" ]