FROM node:16-alpine
WORKDIR /trekie

RUN mkdir -p /trekie/web
RUN mkdir -p /trekie/shared

RUN npm install -g pnpm

COPY ./web/pnpm-lock.yaml /trekie/web
RUN cd web && pnpm fetch
COPY ./web /trekie/web
COPY ./shared /trekie/shared
RUN cd web && pnpm install --offline

WORKDIR /trekie/web
CMD [ "pnpm", "run", "dev" ]